# Generated by Django 4.2.7 on 2023-12-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('telefone', models.CharField(max_length=13)),
                ('nome', models.CharField(max_length=40)),
                ('nomePaciente', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('dependente', models.CharField(max_length=40)),
                ('dataNascimento', models.DateField()),
                ('senha', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
