# Generated by Django 4.2.7 on 2023-12-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_client', '0002_rename_nome_cliente_nomeresponsavel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='senha',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='password',
            field=models.CharField(max_length=15),
        ),
    ]
