# Generated by Django 4.2.7 on 2023-11-18 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=11, unique=True)),
                ('nome', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('dependente', models.CharField(max_length=40)),
                ('senha', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
