# Generated by Django 4.2.7 on 2023-12-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_funcionario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='senha',
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='password',
            field=models.CharField(max_length=15),
        ),
    ]
