# Generated by Django 4.2.7 on 2023-11-18 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_funcionario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='dependente',
        ),
    ]
