# Generated by Django 4.2.7 on 2023-12-13 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_funcionario', '0002_remove_funcionario_senha_alter_funcionario_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='dataNascimento',
            new_name='data_nascimento',
        ),
    ]
