# Generated by Django 4.2.7 on 2023-11-19 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_funcionario', '0002_remove_funcionario_dependente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11, message='telefone deve ter 11 digitos')]),
        ),
    ]
